// Code generated by Kitex v0.8.0. DO NOT EDIT.

package videoservice

import (
	"context"
	video "douyin/src/kitex_gen/video"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error)
	PublishAction(ctx context.Context, req *video.PublishActionRequest, callOptions ...callopt.Option) (r *video.PublishActionResponse, err error)
	PublishList(ctx context.Context, req *video.PublishListRequest, callOptions ...callopt.Option) (r *video.PublishListResponse, err error)
	PublishIDList(ctx context.Context, userId int64, callOptions ...callopt.Option) (r []int64, err error)
	VideoInfo(ctx context.Context, req *video.VideoInfoRequest, callOptions ...callopt.Option) (r *video.Video, err error)
	VideoInfoList(ctx context.Context, req *video.VideoInfoListRequest, callOptions ...callopt.Option) (r []*video.Video, err error)
	WorkCount(ctx context.Context, userId int64, callOptions ...callopt.Option) (r int64, err error)
	AuthorId(ctx context.Context, videoId int64, callOptions ...callopt.Option) (r int64, err error)
	VideoExist(ctx context.Context, videoId int64, callOptions ...callopt.Option) (r bool, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) Feed(ctx context.Context, req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, req)
}

func (p *kVideoServiceClient) PublishAction(ctx context.Context, req *video.PublishActionRequest, callOptions ...callopt.Option) (r *video.PublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishAction(ctx, req)
}

func (p *kVideoServiceClient) PublishList(ctx context.Context, req *video.PublishListRequest, callOptions ...callopt.Option) (r *video.PublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, req)
}

func (p *kVideoServiceClient) PublishIDList(ctx context.Context, userId int64, callOptions ...callopt.Option) (r []int64, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishIDList(ctx, userId)
}

func (p *kVideoServiceClient) VideoInfo(ctx context.Context, req *video.VideoInfoRequest, callOptions ...callopt.Option) (r *video.Video, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoInfo(ctx, req)
}

func (p *kVideoServiceClient) VideoInfoList(ctx context.Context, req *video.VideoInfoListRequest, callOptions ...callopt.Option) (r []*video.Video, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoInfoList(ctx, req)
}

func (p *kVideoServiceClient) WorkCount(ctx context.Context, userId int64, callOptions ...callopt.Option) (r int64, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.WorkCount(ctx, userId)
}

func (p *kVideoServiceClient) AuthorId(ctx context.Context, videoId int64, callOptions ...callopt.Option) (r int64, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AuthorId(ctx, videoId)
}

func (p *kVideoServiceClient) VideoExist(ctx context.Context, videoId int64, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoExist(ctx, videoId)
}
