FROM golang:1.22.1-bookworm AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /douyin

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o api api/main.go

FROM scratch

COPY ./config/config.yaml /config/config.yaml
COPY --from=builder /douyin/api /