jwt_key: chux1no8l6

snowflake:
  start_time: "2023-06-28"
  machine_id: 1

oss:
  endpoint: oss.chuxin0816.com
  access_key_id: example
  access_key_secret: example
  bucket_name: example

hertz:
  host: 0.0.0.0
  port: 8888

log:
  path: ../logs
  max_size: 10485760 #10M
  max_backups: 10
  max_age: 30

database:
  mysql-master:
    user: root
    password: 123456
    host: mysql-master
    port: 3306
    dbname: douyin

  mysql-slaves:
    - user: root
      password: 123456
      host: mysql-slave
      port: 3306
      dbname: douyin

  redis:
    master_name: mymaster
    sentinel_addrs:
      - redis-sentinel1:26379
      - redis-sentinel2:26379
      - redis-sentinel3:26379
    password: 123456
    db: 0

  nebula:
    host: nebula-graphd
    port: 9669
    user: root
    password: nebula
    space: douyin

consul:
  consul_addr: consul:8500
  user_addr: user:8891
  video_addr: video:8892
  favorite_addr: favorite:8893
  comment_addr: comment:8894
  relation_addr: relation:8895
  message_addr: message:8896

kafka:
  brokers:
    - "kafka-0:9092"
    - "kafka-1:9092"
    - "kafka-2:9092"

open_telemetry:
  api_name: "api"
  user_name: "user"
  video_name: "video"
  favorite_name: "favorite"
  comment_name: "comment"
  relation_name: "relation"
  message_name: "message"
  metric_addr: ":9990"
  jaeger_addr: "jaeger:4318"
