apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: ghcr.io/chuxin0816/douyin:comment
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 8894
---
kind: Service
apiVersion: v1
metadata:
  name: comment-svc
spec:
  selector:
    app: comment
  type: ClusterIP
  ports:
    - name: "8894"
      port: 8894
      targetPort: 8894
