apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: ghcr.io/chuxin0816/douyin:user
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 8891
---
kind: Service
apiVersion: v1
metadata:
  name: user-svc
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - name: "8891"
      port: 8891
      targetPort: 8891
