apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
spec:
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
        - name: mysql-master
          image: mysql:8.0.37
          resources:
            limits:
              memory: "8Gi"
              cpu: "4"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "douyin"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/my.cnf
              subPath: my_master.cnf
            - name: init-sql-volume
              mountPath: /docker-entrypoint-initdb.d/douyin.sql
              subPath: douyin.sql
            - name: init-sql-volume
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init_master.sql
      volumes:
        - name: config-volume
          configMap:
            name: mysql-master-config
        - name: init-sql-volume
          configMap:
            name: mysql-init-scripts
        - name: mysql-master-storage
          persistentVolumeClaim:
            claimName: mysql-master-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-svc
spec:
  selector:
    app: mysql-master
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /home/k8s/master/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - paas-cnp-k8s-kce-01  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-master-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
  labels:
    app: mysql-master
data:
  my_master.cnf: |
    [mysqld]
    transaction-isolation = READ-COMMITTED
    max_connections=1000
    log-bin=mysql-bin # 开启 binlog
    binlog-format=ROW # 选择 ROW 模式
    binlog-do-db=douyin
    server_id=1 # 配置 MySQL replaction 需要定义，不要和 canal 的 slaveId 重复
    default_time_zone = '+08:00'
    host-cache-size=0
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql
    pid-file=/var/run/mysqld/mysqld.pid
    [client]
    socket=/var/run/mysqld/mysqld.sock
    !includedir /etc/mysql/conf.d/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  douyin.sql: |
    SET NAMES utf8mb4;
    SET FOREIGN_KEY_CHECKS = 0;

    DROP TABLE IF EXISTS `comment`;
    CREATE TABLE `comment` (
      `id` bigint unsigned NOT NULL,
      `video_id` bigint NOT NULL DEFAULT '0' COMMENT '视频ID',
      `user_id` bigint NOT NULL DEFAULT '0' COMMENT '用户ID',
      `content` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '评论内容',
      `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      PRIMARY KEY (`id`),
      KEY `idx_video_id` (`video_id`),
      KEY `idx_user_id` (`user_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    DROP TABLE IF EXISTS `favorite`;
    CREATE TABLE `favorite` (
      `id` bigint unsigned NOT NULL,
      `user_id` bigint NOT NULL DEFAULT '0' COMMENT '用户ID',
      `video_id` bigint NOT NULL DEFAULT '0' COMMENT '视频ID',
      PRIMARY KEY (`id`),
      UNIQUE KEY `idx_user_video` (`user_id`,`video_id`) USING BTREE,
      KEY `idx_video_id` (`video_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    DROP TABLE IF EXISTS `user`;
    CREATE TABLE `user` (
      `id` bigint unsigned NOT NULL COMMENT '用户ID',
      `name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '用户名',
      `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '头像地址',
      `background_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '背景图地址',
      `signature` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '个性签名',
      `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      PRIMARY KEY (`id`),
      UNIQUE KEY `idx_name` (`name`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    DROP TABLE IF EXISTS `user_login`;
    CREATE TABLE `user_login` (
      `id` bigint unsigned NOT NULL COMMENT '用户ID',
      `username` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户名',
      `password` char(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '加密密码',
      `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      PRIMARY KEY (`id`),
      UNIQUE KEY `idx_name` (`username`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    DROP TABLE IF EXISTS `video`;
    CREATE TABLE `video` (
      `id` bigint unsigned NOT NULL COMMENT '视频ID',
      `author_id` bigint NOT NULL DEFAULT '0' COMMENT '作者ID',
      `play_url` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '视频地址',
      `cover_url` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '封面地址',
      `upload_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
      `title` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '标题',
      PRIMARY KEY (`id`),
      KEY `idx_author_id` (`author_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

  init_master.sql: |
    CREATE USER slave IDENTIFIED BY 'slave';
    GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'slave'@'%';
    ALTER USER 'slave'@'%' IDENTIFIED WITH mysql_native_password BY 'slave';
    CREATE USER canal IDENTIFIED BY 'canal';  
    GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
    FLUSH PRIVILEGES;
