// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:主键" json:"id"` // 主键
	VideoID    int64     `gorm:"column:video_id;not null" json:"video_id"`
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`
	Content    string    `gorm:"column:content;not null" json:"content"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
