// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	VideoID    int64     `gorm:"column:video_id" json:"video_id"`
	UserID     int64     `gorm:"column:user_id" json:"user_id"`
	Content    string    `gorm:"column:content" json:"content"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
