// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelation = "relations"

// Relation mapped from table <relations>
type Relation struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64 `gorm:"column:user_id" json:"user_id"`
	FollowerID int64 `gorm:"column:follower_id" json:"follower_id"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
