// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelation = "relation"

// Relation mapped from table <relation>
type Relation struct {
	ID         int64 `gorm:"column:id;primaryKey" json:"id"`
	UserID     int64 `gorm:"column:user_id;not null" json:"user_id"`
	FollowerID int64 `gorm:"column:follower_id;not null" json:"follower_id"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
