FROM golang:alpine AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /douyin

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o app api/main.go

FROM scratch

COPY ./config/config.yaml /config/config.yaml
COPY --from=builder /douyin/app /

ENTRYPOINT ["/app"]