// Code generated by Kitex v0.8.0. DO NOT EDIT.

package favoriteservice

import (
	"context"
	favorite "douyin/src/kitex_gen/favorite"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return favoriteServiceServiceInfo
}

var favoriteServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FavoriteService"
	handlerType := (*favorite.FavoriteService)(nil)
	methods := map[string]kitex.MethodInfo{
		"FavoriteAction":    kitex.NewMethodInfo(favoriteActionHandler, newFavoriteServiceFavoriteActionArgs, newFavoriteServiceFavoriteActionResult, false),
		"FavoriteList":      kitex.NewMethodInfo(favoriteListHandler, newFavoriteServiceFavoriteListArgs, newFavoriteServiceFavoriteListResult, false),
		"FavoriteCnt":       kitex.NewMethodInfo(favoriteCntHandler, newFavoriteServiceFavoriteCntArgs, newFavoriteServiceFavoriteCntResult, false),
		"TotalFavoritedCnt": kitex.NewMethodInfo(totalFavoritedCntHandler, newFavoriteServiceTotalFavoritedCntArgs, newFavoriteServiceTotalFavoritedCntResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "favorite",
		"ServiceFilePath": `../../idl/favorite.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func favoriteActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteActionArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteActionResult)
	success, err := handler.(favorite.FavoriteService).FavoriteAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteActionArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteActionArgs()
}

func newFavoriteServiceFavoriteActionResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteActionResult()
}

func favoriteListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteListArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteListResult)
	success, err := handler.(favorite.FavoriteService).FavoriteList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteListArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteListArgs()
}

func newFavoriteServiceFavoriteListResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteListResult()
}

func favoriteCntHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteCntArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteCntResult)
	success, err := handler.(favorite.FavoriteService).FavoriteCnt(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newFavoriteServiceFavoriteCntArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteCntArgs()
}

func newFavoriteServiceFavoriteCntResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteCntResult()
}

func totalFavoritedCntHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceTotalFavoritedCntArgs)
	realResult := result.(*favorite.FavoriteServiceTotalFavoritedCntResult)
	success, err := handler.(favorite.FavoriteService).TotalFavoritedCnt(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newFavoriteServiceTotalFavoritedCntArgs() interface{} {
	return favorite.NewFavoriteServiceTotalFavoritedCntArgs()
}

func newFavoriteServiceTotalFavoritedCntResult() interface{} {
	return favorite.NewFavoriteServiceTotalFavoritedCntResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) FavoriteAction(ctx context.Context, req *favorite.FavoriteActionRequest) (r *favorite.FavoriteActionResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteActionArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteActionResult
	if err = p.c.Call(ctx, "FavoriteAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteList(ctx context.Context, req *favorite.FavoriteListRequest) (r *favorite.FavoriteListResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteListArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteListResult
	if err = p.c.Call(ctx, "FavoriteList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteCnt(ctx context.Context, userId int64) (r int64, err error) {
	var _args favorite.FavoriteServiceFavoriteCntArgs
	_args.UserId = userId
	var _result favorite.FavoriteServiceFavoriteCntResult
	if err = p.c.Call(ctx, "FavoriteCnt", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TotalFavoritedCnt(ctx context.Context, userId int64) (r int64, err error) {
	var _args favorite.FavoriteServiceTotalFavoritedCntArgs
	_args.UserId = userId
	var _result favorite.FavoriteServiceTotalFavoritedCntResult
	if err = p.c.Call(ctx, "TotalFavoritedCnt", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
