FROM golang:alpine AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /douyin

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN cd rpc/service/publish && sh build.sh

FROM ubuntu:jammy

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends --fix-missing \
    ffmpeg 

COPY ./config/config.yaml /config/config.yaml
COPY --from=builder /douyin/rpc/service/publish/output/bin/publish /

ENTRYPOINT ["/publish"]
