FROM golang:1.22.1-bookworm AS builder

ENV GO111MODULE=on \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /douyin

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN cd rpc/service/publish && sh build.sh

FROM scratch

COPY ./config/config.yaml /config/config.yaml

COPY --from=builder /douyin/rpc/service/message/output/bin/message /