// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID         int64  `gorm:"column:id;primaryKey" json:"id"`
	FromUserID int64  `gorm:"column:from_user_id;not null;comment:发送者ID" json:"from_user_id"` // 发送者ID
	ToUserID   int64  `gorm:"column:to_user_id;not null;comment:接收者ID" json:"to_user_id"`     // 接收者ID
	ConvertID  string `gorm:"column:convert_id;not null;comment:会话ID" json:"convert_id"`      // 会话ID
	Content    string `gorm:"column:content;not null;comment:消息内容" json:"content"`            // 消息内容
	CreateTime int64  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`    // 创建时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
