// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelation = "relation"

// Relation mapped from table <relation>
type Relation struct {
	ID         int64 `gorm:"column:id;primaryKey" json:"id"`
	AuthorID   int64 `gorm:"column:author_id;not null;comment:作者ID" json:"author_id"`     // 作者ID
	FollowerID int64 `gorm:"column:follower_id;not null;comment:粉丝ID" json:"follower_id"` // 粉丝ID
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
