// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID              int64     `gorm:"column:id;primaryKey;comment:用户ID" json:"id"`                                           // 用户ID
	Name            string    `gorm:"column:name;not null;comment:用户名" json:"name"`                                          // 用户名
	Avatar          string    `gorm:"column:avatar;not null;comment:头像地址" json:"avatar"`                                     // 头像地址
	BackgroundImage string    `gorm:"column:background_image;not null;comment:背景图地址" json:"background_image"`                // 背景图地址
	Signature       string    `gorm:"column:signature;not null;comment:个性签名" json:"signature"`                               // 个性签名
	CreateTime      time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime      time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
