// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID            int64     `gorm:"column:id;primaryKey;comment:视频ID" json:"id"`                                           // 视频ID
	AuthorID      int64     `gorm:"column:author_id;not null;comment:作者ID" json:"author_id"`                               // 作者ID
	PlayURL       string    `gorm:"column:play_url;not null;comment:视频地址" json:"play_url"`                                 // 视频地址
	CoverURL      string    `gorm:"column:cover_url;not null;comment:封面地址" json:"cover_url"`                               // 封面地址
	UploadTime    time.Time `gorm:"column:upload_time;not null;default:CURRENT_TIMESTAMP;comment:上传时间" json:"upload_time"` // 上传时间
	FavoriteCount int64     `gorm:"column:favorite_count;not null;comment:点赞数" json:"favorite_count"`                      // 点赞数
	Title         string    `gorm:"column:title;not null;comment:标题" json:"title"`                                         // 标题
	CommentCount  int64     `gorm:"column:comment_count;not null;comment:评论数" json:"comment_count"`                        // 评论数
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
