name: Docker Image CI

on:
  push:
    branches: ['main']
    paths-ignore: ['README.md', 'LICENSE', 'docker-compose.yml', '.gitignore', '.github/**']
  pull_request:
    branches: ['main']
    paths-ignore: ['README.md', 'LICENSE', 'docker-compose.yml', '.gitignore', '.github/**']

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [api, comment, favorite, feed, message, publish, relation, user]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push ${{ matrix.component }} image
        uses: docker/build-push-action@v5
        with:
          file: ./cmd/docker/${{ matrix.component }}/Dockerfile
          push: true
          tags: ghcr.io/chuxin0816/douyin:${{ matrix.component }}
          platforms: linux/amd64,linux/arm64